apiVersion: v1
kind: Service
metadata:
  name: upravljanjestrani-service
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32229
  selector:
    app: upravljanjeStrani